### PR TITLE
ETA (Estimated Time of Arrival) Class

### PR DESCRIPTION
**Pull request by KennethRuan**
The PR adds in the ETA class to be used in conjunction with the Weather class. Currently, eta.py uses a method from the Overhaul PR, but it can be properly integrated if the overhaul is approved.

### CODE REVIEW

**Comment by KennethRuan** [comment]
During the checks, it seems that there is an issue with the evaluation of `os.path.join` on line 278 of `eta.py` that is not present locally.

Line 34 of the testing output shows:
```
For reference, the program attempted to open /home/runner/work/strategy_xv/strategy_xv/routemodel/eta/eta.py/../current_location.txt
```

Looking into it, but any suggestions would be greatly appreciated.

**Comment by probro27** [comment]
@KennethRuan Yeah I'll check it out! I'm not sure what's causing the errors

**Comment by ryan-lam** [comment]
I haven't looked at the code yet but is it compatible with [routemodelv2](https://github.com/uw-midsun/strategy_xv/tree/overhaul)?

**Comment by probro27** [comment]
@KennethRuan I tried using this: `os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__), "current_location.txt")`
and got the file path without `..`
but the error still persists
image

**Review by probro27 — APPROVED** [review]
@KennethRuan Looks good to me! I think we can merge it in.

**Pull request merged**
