### PR TITLE
Migrating car dynamics code

### PR DESCRIPTION
**Pull request by aliciabremer**
* Moving code from old repo for modelling car forces
* Updating documentation

### CODE REVIEW

**Review by probro27 — APPROVED** [review]
So I think the code itself is fine and we can approve this, but we might want to change our approach on using energy profile because the old code is kind of weird. 
Especially in energy used function. 
They take in the distance as a parameter in the code, but they also have a dist variable which they find from the energy profile as the distance between two points is different in every loop. 
So might want to check it out. 
Apart from that think we can reuse most of this. 
Also need to confirm min max velocity and mass of car along with the Crr, CdA and max force default values of parameters for Car class.

**Comment by aliciabremer** [comment]
Yeah I looked at the energy_used and it doesn't seem like the distance parameter is being used at the moment which is weird - I'll take it out right now. The other things can probably be confirmed later on

**Review by probro27 — COMMENTED** [review]
Looks good to me tbh. 
Let's add this. Only thing is that the current elevation profile being generated is (lat, long, elevation). this expects [elevation, distance]. So we might want to format the code to use our current elevation profile, or if we want to use this code then we can create another function to convert our elevation profile to this one.

**Comment by ryan-lam** [comment]
@aliciabremer i worked on + done the car forces. up to u if u wanna remove the code related to forces.

https://github.com/uw-midsun/strategy_xv/pull/16

**Pull request closed without merging**
